version: '3.8'
services:
  nest-api:
    container_name: airbnbapi
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - mysql_db
    env_file: .env
    networks:
      - node-network

  mysql_db:
    image: mysql
    container_name: mysql_db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=db_airbnb
    env_file:
      - .env
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
      - node-network

volumes:
  mysql_db:
    driver: local
networks:
  node-network: